steps:
- id: 'Vanillasoft-tf'
  name: 'alpine'
  entrypoint: 'sh'  
  args: 
  - '-c'
  - | 
      echo "***********************"
      echo "$BRANCH_NAME"
      echo "***********************"

- id: 'tf init'
  name: 'hashicorp/terraform:1.0.0'
  entrypoint: 'sh'
  args: 
  - '-c'
  - |
          cd "project/${_ENV} "
          ls -al
          env=${dir%*/}
          env=${_ENV}
          echo ""
          echo "*************** TERRAFORM INIT ******************"
          echo "******* At project: ${env} ********"
          echo "*************************************************"
          terraform init || exit 1
          cd ../../
        

# [START tf-plan]
- id: 'tf plan'
  name: 'hashicorp/terraform:1.0.0'
  entrypoint: 'sh'
  args: 
  - '-c'
  - | 
          cd "project/${_ENV} "  
          env=${dir%*/}
          env=${_ENV}  
          echo ""
          echo "*************** TERRAFOM PLAN ******************"
          echo "******* At project: ${env} ********"
          echo "*************************************************"
          terraform plan || exit 1
          cd ../../ 
# [END tf-plan]
substitutions:
  _ENV: temp
options:
  logging: CLOUD_LOGGING_ONLY
