steps:

  # Step 1: Fetch the secret from Secret Manager and write it to /workspace/.smbcredentials
  - name: gcr.io/cloud-builders/gcloud
    id: FetchSecret
    entrypoint: bash
    args:
      - -c
      - |
        gcloud secrets versions access latest \
          --secret="commit-db-secret" \
          > /workspace/project/app-deploy/.env
         cat /workspace/project/app-deploy/.env


  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '--no-cache'
      - '-t'
      - '$_AR_HOSTNAME/$_PROJECT_ID/$_REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA'
      - '-f'
      - '/workspace/project/app-deploy/Dockerfile'
      - '/workspace/project/app-deploy'
    id: Build

  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - '$_AR_HOSTNAME/$_PROJECT_ID/$_REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA'
    id: Push

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    args:
      - run
      - deploy
      - '$_SERVICE_NAME'
      - '--image=$_AR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA'
      - '--platform=managed'
      - '--region=$_DEPLOY_REGION'
      - '--allow-unauthenticated'
      - '--quiet'
      - '--port=8080'
      - '--min-instances=1'
      - '--max-instances=10'
      - '--cpu=2'
      - '--memory=8Gi'
      - '--service-account=cloud-run@commit-hr-emmanuelo-infra.iam.gserviceaccount.com'
      - '--add-cloudsql-instances=commit-hr-emmanuelo-data:northamerica-northeast1:test-cloud-sql'
      - '--set-env-vars=DB_HOST=/cloudsql/commit-hr-emmanuelo-data:northamerica-northeast1:test-cloud-sql'
    id: Deploy
    entrypoint: gcloud


substitutions:
  _AR_HOSTNAME: northamerica-northeast1-docker.pkg.dev
  _PROJECT_ID: commit-hr-emmanuelo-infra
  _REPO_NAME: commit-task
  _SERVICE_NAME: commit-docker
  _DEPLOY_REGION: northamerica-northeast1
  _PLATFORM: managed
  _TRIGGER_ID: 86e1068f-9ba9-4b3e-964f-3178b331dc25

tags:
  - gcp-cloud-build-deploy-cloud-run
  - gcp-cloud-build-deploy-cloud-run-managed
  - commit-docker-service

options:
  substitutionOption: ALLOW_LOOSE
  logging: CLOUD_LOGGING_ONLY
